### ISSUE TITLE
En tant que joueur 1, je veux pouvoir faire pivoter mes blocks 

### ISSUE THREAD

**Issue by yadPe** [JeanCarrillo/super-block-heroes#21]
Salut
https://github.com/JeanCarrillo/super-block-heroes/blob/50da2532e4d17b9fcaaf4d4c1b148e46727eb517/src/app/constants/keyboard.ts#L9

**Comment by yadPe** [comment]
Ah c'est bon j'ai trouvé c'est espace !

**Comment by Jean-Carrillo** [comment]
😂
Je te présente la formidable syntaxe pour 'spacebar'.
